### ISSUE TITLE
How to extract .jaf files

### ISSUE THREAD

**Issue by alan-zxs** [nunuhara/r10-mod-system#1]
done

**Comment by nunuhara** [comment]
There is currently no decompiler that is able to decompile .jaf files from Rance10.ain.
All the .jaf files in this repo were written from scratch, and they work be overriding functions rather than rewriting them.

In other words, it is possible to inject code from a .jaf file into Rance10.ain, but it is not possible to get .jaf files out of it.

**Comment by linakima** [comment]
Sad news. Thank you for explaining

**Comment by alan-zxs** [comment]
Sad news. Thank you for explaining
